create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    enabled boolean not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_app_users_username unique (username),
    constraint chk_app_users_role check (role in ('ADMIN', 'STAFF'))
);

create table customers (
    id bigint generated by default as identity primary key,
    full_name varchar(255),
    phone_number varchar(255) not null,
    email varchar(255),
    address varchar(255),
    city varchar(255),
    state varchar(255),
    postal_code varchar(255),
    notes varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_customers_phone_number unique (phone_number)
);

create table gold_rates (
    id bigint generated by default as identity primary key,
    metal_type varchar(255) not null,
    purity varchar(255) not null,
    rate_per_gram numeric(38, 2) not null,
    rate_date date not null,
    source varchar(255),
    notes varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6)
);

create table jewellery_items (
    id bigint generated by default as identity primary key,
    item_name varchar(255),
    category varchar(255),
    metal_type varchar(255),
    purity varchar(255),
    gross_weight numeric(38, 2),
    net_weight numeric(38, 2),
    stone_weight numeric(38, 2),
    gold_rate_per_gram numeric(38, 2),
    stone_price numeric(38, 2),
    making_charges numeric(38, 2),
    tax_percentage numeric(38, 2),
    discount numeric(38, 2),
    gold_value numeric(38, 2),
    tax_amount numeric(38, 2),
    purchase_cost numeric(38, 2),
    selling_price numeric(38, 2),
    status varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6)
);

create table invoices (
    id bigint generated by default as identity primary key,
    invoice_number varchar(255) not null,
    customer_id bigint not null,
    customer_name varchar(255),
    customer_phone_number varchar(255),
    item_id bigint not null,
    item_name varchar(255),
    category varchar(255),
    metal_type varchar(255),
    purity varchar(255),
    quantity integer not null,
    gross_weight numeric(38, 2),
    net_weight numeric(38, 2),
    stone_weight numeric(38, 2),
    gold_rate_per_gram numeric(38, 2),
    gold_value numeric(38, 2),
    stone_price numeric(38, 2),
    making_charges numeric(38, 2),
    subtotal numeric(38, 2),
    tax_percentage numeric(38, 2),
    tax_amount numeric(38, 2),
    discount numeric(38, 2),
    unit_final_amount numeric(38, 2),
    final_amount numeric(38, 2),
    order_status varchar(255),
    payment_status varchar(255),
    payment_method varchar(255),
    notes varchar(255),
    invoice_date timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_invoices_invoice_number unique (invoice_number)
);

create table sales (
    id bigint generated by default as identity primary key,
    invoice_number varchar(255) not null,
    customer_id bigint not null,
    customer_name varchar(255),
    customer_phone_number varchar(255),
    item_id bigint not null,
    item_name varchar(255),
    category varchar(255),
    metal_type varchar(255),
    purity varchar(255),
    gross_weight numeric(38, 2),
    net_weight numeric(38, 2),
    stone_weight numeric(38, 2),
    gold_rate_per_gram numeric(38, 2),
    gold_value numeric(38, 2),
    stone_price numeric(38, 2),
    making_charges numeric(38, 2),
    tax_percentage numeric(38, 2),
    tax_amount numeric(38, 2),
    discount numeric(38, 2),
    final_amount numeric(38, 2),
    payment_status varchar(255),
    payment_method varchar(255),
    notes varchar(255),
    sale_date timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_sales_invoice_number unique (invoice_number)
);

create index idx_gold_rates_lookup on gold_rates (metal_type, purity, rate_date);
create index idx_jewellery_items_status on jewellery_items (status);
create index idx_invoices_customer_name on invoices (customer_name);
create index idx_invoices_payment_status on invoices (payment_status);
create index idx_sales_customer_name on sales (customer_name);
create index idx_sales_payment_status on sales (payment_status);
