create table user_invites (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    token_hash varchar(255) not null,
    role varchar(255) not null,
    expires_at timestamp(6) not null,
    created_at timestamp(6),
    accepted_at timestamp(6),
    constraint uk_user_invites_token_hash unique (token_hash),
    constraint chk_user_invites_role check (role in ('ADMIN', 'STAFF'))
);

create index idx_user_invites_username on user_invites (username);
create index idx_user_invites_pending on user_invites (token_hash, accepted_at);
