spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jewelflow
    username: jewelflow_user
    password: jewelflow_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080